logging:
  file_path: "./app.log"
  max_size: "20m"
  max_files: 5
  console_enabled: true
  log_level: "debug"

smpp_peers:
  - id: osmocom-msc
    system_id: "smsgw"
    password: "smsgw"
    ipaddress: "10.90.250.42"
    system_type: "default"
    port: 2775
    reconnect_interval: 10000
    source_addr_ton: 1
    source_addr_npi: 1
    dest_addr_ton: 1
    dest_addr_npi: 1
    route_regex: "^\\334201.*" # Match MSISDNs starting with +123
    default: true
  - id: jasmin-sms-gw
    system_id: "svinson"
    password: "svinson"
    ipaddress: "10.90.250.170"
    system_type: "default"
    port: 2775
    reconnect_interval: 10000
    source_addr_ton: 1
    source_addr_npi: 1
    dest_addr_ton: 1
    dest_addr_npi: 1
    route_regex: "^\\+456.*" # Match MSISDNs starting with +456
    default: false # Default for unmatched MSISDNs

smpp_server:
  bind_ip: "0.0.0.0"
  port: 2775 # 
  auth:
    - system_id: "client1"
      password: "client1pass"
    - system_id: "client2"
      password: "client2pass"

http_server:
  bind_ip: "0.0.0.0"
  port: 8080
  kamailio_url: "http://10.90.250.53:8080/sms" # 
